[programs.localnet]
swap_coontract_test = "EBwKXJ7MM2WYSxRJQJMA76h7Exgr3mjUddcNq152bExw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
# cluster = "devnet"
# wallet = "/home/kwiscion/.config/solana/id.json"
cluster = "localnet"
wallet = "/home/biboux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
