[programs.devnet]
neo_swap = "CCzejnwJTxcYzaKioMKoVWkDKnR265FE9eYdnKGVWahx"
[programs.localnet]
neo_swap = "CCzejnwJTxcYzaKioMKoVWkDKnR265FE9eYdnKGVWahx"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/home/biboux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
