[programs.devnet]
neo_swap = "28c8n7mgURdiuo1n2Po7kjMNqnhNihMC5aJLTG6bLn5E"
[programs.localnet]
neo_swap = "28c8n7mgURdiuo1n2Po7kjMNqnhNihMC5aJLTG6bLn5E"
[programs.mainnet]
neo_swap = "5wW12LWQuwGW2mNHpDMqQSp5ijY41JgLGd1maGcywWA4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster =   "https://purple-alpha-orb.solana-devnet.quiknode.pro/da30b6f0da74d8a084df9aac72c5da241ab4f9a8/"
# cluster = "https://api.devnet.solana.com"
# cluster = "localnet"
wallet = "/home/biboux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
