[programs.devnet]
neo_swap = "CtZHiWNnLu5rQuTN3jo7CmYDR8Wns6qXHn7taPvmnACp"
[programs.localnet]
neo_swap = "CtZHiWNnLu5rQuTN3jo7CmYDR8Wns6qXHn7taPvmnACp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster =   "https://purple-alpha-orb.solana-devnet.quiknode.pro/da30b6f0da74d8a084df9aac72c5da241ab4f9a8/"
# cluster = "https://api.devnet.solana.com"
# cluster = "localnet"
wallet = "/home/biboux/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
